(function(){var i=/\blang(?:uage)?-(?!\*)(\w+)\b/i,g=self.Prism={languages:{insertBefore:function(a,b,d,c){var c=c||g.languages,f=c[a],e={},h;for(h in f)if(f.hasOwnProperty(h)){if(h==b)for(var i in d)d.hasOwnProperty(i)&&(e[i]=d[i]);e[h]=f[h]}return c[a]=e},DFS:function(a,b){for(var d in a)b.call(a,d,a[d]),"[object Object]"===Object.prototype.toString.call(a)&&g.languages.DFS(a[d],b)}},highlightAll:function(a,b){for(var d=document.querySelectorAll('code[class*="language-"], [class*="language-"] code, code[class*="lang-"], [class*="lang-"] code'),
c=0,f;f=d[c++];)g.highlightElement(f,!0===a,b)},highlightElement:function(a,b,d){for(var c,f,e=a;e&&!i.test(e.className);)e=e.parentNode;e&&(c=(e.className.match(i)||[,""])[1],f=g.languages[c]);if(f&&(a.className=a.className.replace(i,"").replace(/\s+/g," ")+" language-"+c,e=a.parentNode,/pre/i.test(e.nodeName)&&(e.className=e.className.replace(i,"").replace(/\s+/g," ")+" language-"+c),e=a.textContent.trim())){var e=e.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\u00a0/g,
" "),h={element:a,language:c,grammar:f,code:e};g.hooks.run("before-highlight",h);b&&self.Worker?(a=new Worker(g.filename),a.onmessage=function(a){h.highlightedCode=k.stringify(JSON.parse(a.data));h.element.innerHTML=h.highlightedCode;d&&d.call(h.element);g.hooks.run("after-highlight",h)},a.postMessage(JSON.stringify({language:h.language,code:h.code}))):(h.highlightedCode=g.highlight(h.code,h.grammar),h.element.innerHTML=h.highlightedCode,d&&d.call(a),g.hooks.run("after-highlight",h))}},highlight:function(a,
b){return k.stringify(g.tokenize(a,b))},tokenize:function(a,b){var d=g.Token,c=[a],f=b.rest;if(f){for(var e in f)b[e]=f[e];delete b.rest}a:for(e in b)if(b.hasOwnProperty(e)&&b[e])for(var f=b[e],h=f.inside,i=!!f.lookbehind||0,f=f.pattern||f,k=0;k<c.length;k++){var j=c[k];if(c.length>a.length)break a;if(!(j instanceof d)){f.lastIndex=0;var l=f.exec(j);if(l){i&&(i=l[1].length);var n=l.index-1+i,l=l[0].slice(i),m=n+l.length,n=j.slice(0,n+1),j=j.slice(m+1),m=[k,1];n&&m.push(n);l=new d(e,h?g.tokenize(l,
h):l);m.push(l);j&&m.push(j);Array.prototype.splice.apply(c,m)}}}return c},hooks:{all:{},add:function(a,b){var d=g.hooks.all;d[a]=d[a]||[];d[a].push(b)},run:function(a,b){var d=g.hooks.all[a];if(d&&d.length)for(var c=0,f;f=d[c++];)f(b)}}},k=g.Token=function(a,b){this.type=a;this.content=b};k.stringify=function(a){if("string"==typeof a)return a;if("[object Array]"==Object.prototype.toString.call(a)){for(var b=0;b<a.length;b++)a[b]=k.stringify(a[b]);return a.join("")}a={type:a.type,content:k.stringify(a.content),
tag:"span",classes:["token",a.type],attributes:{}};"comment"==a.type&&(a.attributes.spellcheck="true");g.hooks.run("wrap",a);var d="";for(b in a.attributes)d+=b+'="'+(a.attributes[b]||"")+'"';return"<"+a.tag+' class="'+a.classes.join(" ")+'" '+d+">"+a.content+"</"+a.tag+">"};if(self.document){var j=document.getElementsByTagName("script");if(j=j[j.length-1])g.filename=j.src,document.addEventListener&&!j.hasAttribute("data-manual")&&document.addEventListener("DOMContentLoaded",g.highlightAll)}else self.addEventListener("message",
function(a){a=JSON.parse(a.data);self.postMessage(JSON.stringify(g.tokenize(a.code,g.languages[a.language])));self.close()},!1)})();
Prism.languages.markup={comment:/&lt;!--[\w\W]*?--(&gt;|&gt;)/g,prolog:/&lt;\?.+?\?&gt;/,doctype:/&lt;!DOCTYPE.+?&gt;/,cdata:/&lt;!\[CDATA\[[\w\W]+?]]&gt;/i,tag:{pattern:/&lt;\/?[\w:-]+\s*[\w\W]*?&gt;/gi,inside:{tag:{pattern:/^&lt;\/?[\w:-]+/i,inside:{punctuation:/^&lt;\/?/,namespace:/^[\w-]+?:/}},"attr-value":{pattern:/=(('|")[\w\W]*?(\2)|[^\s>]+)/gi,inside:{punctuation:/=/g}},punctuation:/\/?&gt;/g,"attr-name":{pattern:/[\w:-]+/g,inside:{namespace:/^[\w-]+?:/}}}},entity:/&amp;#?[\da-z]{1,8};/gi};
Prism.hooks.add("wrap",function(i){"entity"===i.type&&(i.attributes.title=i.content.replace(/&amp;/,"&"))});Prism.languages.css={comment:/\/\*[\w\W]*?\*\//g,atrule:/@[\w-]+?(\s+[^;{]+)?(?=\s*{|\s*;)/gi,url:/url\((["']?).*?\1\)/gi,selector:/[^\{\}\s][^\{\}]*(?=\s*\{)/g,property:/(\b|\B)[a-z-]+(?=\s*:)/ig,string:/("|')(\\?.)*?\1/g,important:/\B!important\b/gi,ignore:/&(lt|gt|amp);/gi,punctuation:/[\{\};:]/g};
Prism.languages.markup&&Prism.languages.insertBefore("markup","tag",{style:{pattern:/(&lt;|<)style[\w\W]*?(>|&gt;)[\w\W]*?(&lt;|<)\/style(>|&gt;)/ig,inside:{tag:{pattern:/(&lt;|<)style[\w\W]*?(>|&gt;)|(&lt;|<)\/style(>|&gt;)/ig,inside:Prism.languages.markup.tag.inside},rest:Prism.languages.css}}});
Prism.languages.javascript={comment:{pattern:/(^|[^\\])(\/\*[\w\W]*?\*\/|\/\/.*?(\r?\n|$))/g,lookbehind:!0},string:/("|')(\\?.)*?\1/g,regex:{pattern:/(^|[^/])\/(?!\/)(\[.+?]|\\.|[^/\r\n])+\/[gim]{0,3}(?=\s*($|[\r\n,.;})]))/g,lookbehind:!0},keyword:/\b(var|let|if|else|while|do|for|return|in|instanceof|function|new|with|typeof|try|catch|finally|null|break|continue)\b/g,"boolean":/\b(true|false)\b/g,number:/\b-?(0x)?\d*\.?\d+\b/g,operator:/[-+]{1,2}|!|=?&lt;|=?&gt;|={1,2}|(&amp;){1,2}|\|?\||\?|\*|\//g,
ignore:/&(lt|gt|amp);/gi,punctuation:/[{}[\];(),.:]/g};Prism.languages.markup&&Prism.languages.insertBefore("markup","tag",{script:{pattern:/(&lt;|<)script[\w\W]*?(>|&gt;)[\w\W]*?(&lt;|<)\/script(>|&gt;)/ig,inside:{tag:{pattern:/(&lt;|<)script[\w\W]*?(>|&gt;)|(&lt;|<)\/script(>|&gt;)/ig,inside:Prism.languages.markup.tag.inside},rest:Prism.languages.javascript}}});
Prism.languages.java={comment:{pattern:/(^|[^\\])(\/\*[\w\W]*?\*\/|\/\/.*?(\r?\n|$))/g,lookbehind:!0},string:/("|')(\\?.)*?\1/g,keyword:/\b(abstract|continue|for|new|switch|assert|default|goto|package|synchronized|boolean|do|if|private|this|break|double|implements|protected|throw|byte|else|import|public|throws|case|enum|instanceof|return|transient|catch|extends|int|short|try|char|final|interface|static|void|class|finally|long|strictfp|volatile|const|float|native|super|while)\b/g,"boolean":/\b(true|false)\b/g,
number:/\b0b[01]+\b|\b0x[\da-f]*\.?[\da-fp\-]+\b|\b\d*\.?\d+[e]?[\d]*[df]\b|\W\d*\.?\d+\b/gi,operator:{pattern:/([^\.]|^)([-+]{1,2}|!|=?&lt;|=?&gt;|={1,2}|(&amp;){1,2}|\|?\||\?|\*|\/|%|\^|(&lt;){2}|($gt;){2,3}|:|~)/g,lookbehind:!0},ignore:/&(lt|gt|amp);/gi,punctuation:/[{}[\];(),.:]/g};
(function(){if(window.Prism){var i=/\b([a-z]{3,7}:\/\/|tel:)[\w-+%~/.]+/,g=/\b\S+@[\w.]+[a-z]{2}/,k=/\[([^\]]+)]\(([^)]+)\)/,j=["comment","url","attr-value","string"],a;for(a in Prism.languages){var b=Prism.languages[a];Prism.languages.DFS(b,function(a,c){-1<j.indexOf(a)&&(c.pattern||(c=this[a]={pattern:c}),c.inside=c.inside||{},"comment"==a&&(c.inside["md-link"]=k),c.inside["url-link"]=i,c.inside["email-link"]=g)});b["url-link"]=i;b["email-link"]=g}Prism.hooks.add("wrap",function(a){if(/-link$/.test(a.type)){a.tag=
"a";var c=a.content;if("email-link"==a.type)c="mailto:"+c;else if("md-link"==a.type){var b=a.content.match(k),c=b[2];a.content=b[1]}b="href";0==c.indexOf("name=")&&(b="name",c=c.substring(5));a.attributes[b]=c}})}})();